// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmhFPkc65OAKfb21oB7QZ5uhr47BQ8sow',
    appId: '1:211425707318:web:4d1d040a526afaf374df97',
    messagingSenderId: '211425707318',
    projectId: 'matching-app-0302',
    authDomain: 'matching-app-0302.firebaseapp.com',
    storageBucket: 'matching-app-0302.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw3BO9niZyCH0yg3IfNyJ-HxdcuB_d1yE',
    appId: '1:211425707318:android:c9b98573876cdf2374df97',
    messagingSenderId: '211425707318',
    projectId: 'matching-app-0302',
    storageBucket: 'matching-app-0302.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGrjpfsF1zoatRP_rN5M8fhYFy68fDbXQ',
    appId: '1:211425707318:ios:1b065c4255f876ce74df97',
    messagingSenderId: '211425707318',
    projectId: 'matching-app-0302',
    storageBucket: 'matching-app-0302.firebasestorage.app',
    iosBundleId: 'com.example.matchingApp',
  );
}
